name: deepfacelab
channels:
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.4
  - cudnn=8.4.1
  - python=3.7
  - pip
  - pip:
    - tqdm
    - numpy==1.20
    - numexpr
    - h5py==2.10.0
    - opencv-python==4.1.0.25
    - ffmpeg-python==0.1.17
    - scikit-image==0.14.2
    - scipy==1.4.1
    - colorama
    - tensorflow-gpu==2.5.0
    - pyqt5
    - tf2onnx
    - Flask==1.1.1
    - flask-socketio==4.2.1
    - tensorboardX
    - crc32c
    - jsonschema
    - Jinja2==3.0.3
    - werkzeug==2.0.2
    - itsdangerous==2.0.1
